/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApiCard: typeof import('./components/ApiCard.vue')['default']
    ApiCard2: typeof import('./components/ApiCard2.vue')['default']
    ApiProcess: typeof import('./components/ApiProcess.vue')['default']
    ApiSize: typeof import('./components/ApiSize.vue')['default']
    ApiType: typeof import('./components/ApiType.vue')['default']
    ApiTypeNew: typeof import('./components/ApiTypeNew.vue')['default']
    ContactIcons: typeof import('./components/ContactIcons.vue')['default']
    Contacts: typeof import('./components/Contacts.vue')['default']
    Experiences: typeof import('./components/Experiences.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    FormBasic: typeof import('./components/form/formBasic.vue')['default']
    FormCustom: typeof import('./components/form/formCustom.vue')['default']
    FormTemplate: typeof import('./components/form/FormTemplate.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HomeIcons: typeof import('./components/HomeIcons.vue')['default']
    Loading: typeof import('./components/loading.vue')['default']
    ModalCustom: typeof import('./components/modalCustom.vue')['default']
    Projects: typeof import('./components/Projects.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionAboutMe: typeof import('./components/SectionAboutMe.vue')['default']
    SectionContact: typeof import('./components/SectionContact.vue')['default']
    SectionExperience: typeof import('./components/SectionExperience.vue')['default']
    SectionHome: typeof import('./components/SectionHome.vue')['default']
    SectionProject: typeof import('./components/SectionProject.vue')['default']
    SectionSkill: typeof import('./components/SectionSkill.vue')['default']
    SkillsIcon: typeof import('./components/SkillsIcon.vue')['default']
    Sum: typeof import('./components/Sum.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
