/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/api/': RouteRecordInfo<'/api/', '/api', Record<never, never>, Record<never, never>>,
    '/api/[id]': RouteRecordInfo<'/api/[id]', '/api/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/ex1': RouteRecordInfo<'/ex1', '/ex1', Record<never, never>, Record<never, never>>,
    '/flex-port': RouteRecordInfo<'/flex-port', '/flex-port', Record<never, never>, Record<never, never>>,
    '/landing': RouteRecordInfo<'/landing', '/landing', Record<never, never>, Record<never, never>>,
    '/scroll': RouteRecordInfo<'/scroll', '/scroll', Record<never, never>, Record<never, never>>,
    '/skills': RouteRecordInfo<'/skills', '/skills', Record<never, never>, Record<never, never>>,
    '/swiper': RouteRecordInfo<'/swiper', '/swiper', Record<never, never>, Record<never, never>>,
  }
}
